#! /bin/bash

sudo amazon-linux-extras enable nginx1

### nginx
sudo yum -y install nginx
sudo systemctl start nginx.service
sudo systemctl enable nginx

### git
### sudo yum update
### sudo yum install git

### nvm
### git clone https://github.com/creationix/nvm.git ~/.nvm
### source ~/.nvm/nvm.sh

### cat > ~/.bash_profile <<'EOF'
### net.ipv4.ip_forward = 1
### net.ipv4.conf.eth0.send_redirects = 0
### EOF

### nvm install v14.10.1
### sudo systemctl start nginx.service

